name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    name: Install Dependencies, Run Tests, and Prepare Coverage
    runs-on: ubuntu-latest
    environment: development
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests and generate coverage for all projects
      - name: Run CI pipeline and generate coverage
        run: npm run workspace:ci

      # Cache coverage folders
      - name: Cache coverage folders
        uses: actions/cache/save@v4
        with:
          path: packages/production/*/coverage
          key: cache-coverage

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: install_and_test
    strategy:
      matrix:
        project:
          - glacier-config
          - glacier-context
          - glacier-openapi
          - glacier-http
          - glacier-ioc
          - glacier-logger
          - glacier-reflection
          - glacier-router
          - glacier-schema
          - glacier-utils
          - glacier-openapi
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Restore cached coverage folder
      - name: Restore cached coverage folders
        uses: actions/cache/restore@v4
        with:
          path: packages/production/*/coverage
          key: cache-coverage

      # SonarQube scan for each project
      - name: Run SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/production/${{ matrix.project }}/
