name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    name: Install Dependencies and Run Tests
    runs-on: ubuntu-latest
    environment: development
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'  # Enables automatic dependency caching

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests and pipeline
      - name: Run CI pipeline
        run: npm run workspace:ci

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: install_and_test
    strategy:
      matrix:
        project:
          - glacier-config
          - glacier-context
          - glacier-http
          - glacier-ioc
          - glacier-logger
          - glacier-reflection
          - glacier-router
          - glacier-schema
          - glacier-utils
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js (to reuse cached dependencies if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # SonarQube scan for each project
      - name: Run SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/production/${{ matrix.project }}/
